name: gpt_v2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run code style checks
      run: |
        flake8 gpt_v2/  # 確保代碼風格符合 flake8
        black --check gpt_v2/  # 確認代碼符合 black 格式

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}/gpt_v2  # 設定 PYTHONPATH 指向 src 目錄
      run: |
        pytest
